version: '3.4'

services:
  tr-mongo:
    image: mongo:latest
    container_name: 'tr-mongo'
    command: --auth
    ports:
      - 27017:27017
    volumes:
      - './data/mongo:/data/db:delegated'
      - './data/seed:/teemaderegister/teemaderegister:delegated'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  tr-node: 
    container_name: 'tr-node'
    depends_on:
      - tr-mongo
    build:
      context: '../teemaderegister-be'
    ports:
      - '3000:3000'
      - '9000:9000'
    volumes:
      - '../teemaderegister-be:/home/node/app:delegated'
      - '../local-dev/data:/home/node/data:delegated'
    environment:
      MONGODB_URI: mongodb://root:root@tr-mongo/teemaderegister?authSource=admin
      MONGODB_TESTS_URI: mongodb://root:root@tr-mongo/teemaderegister-test?authSource=admin
      MONGOOSE_DEBUG: 'true'
      SECRET: this is the secret secret secret 12356
      TOKEN_EXPIRES_IN_SECONDS: 86400
      TOKEN_UPDATE_IN_SECONDS: 3600
      LOGIN_ALLOWED_ATTEMPTS: 5
      LOGIN_ATTEMPT_BLOCK_DELAY_IN_MS: 3600000
      PORT: 3000
      NODE_ENV: development
      LOG_LEVEL: 4
      APP_NAME: teemaderegister
      SITE_URL: http://localhost:8080
      UPLOAD_DIR: ../data/uploads/
      UPLOAD_FILE_SIZE_LIMIT_IN_MB: 100
      PROFILE_PIC_MAX_SIZE_IN_MB: 10
      PROFILE_PIC_FULL_SIDE_PX: 400
      PROFILE_PIC_THUMB_SIDE_PX: 64
      PASSWORD_RESET_TOKEN_EXPIRES: 3600000
      PASSWORD_RESET_LINK_LIMIT: 300000
      MAILSERVICE_HOST: smtp.mailgun.org
      MAILSERVICE_PORT: 587
      MAILSERVICE_USERNAME: postmaster@sandbox5ebcec8bb7a74f2e94c35289d63959fd.mailgun.org
      MAILSERVICE_PASSWORD: c63d598dcf032c9f4f251fae99281c89
      EMAIL_SENDER: teemaderegister@tlu.ee
      EMAIL_SENDER_NAME: Teemaderegister
      TOPICS_EXPIRE_IN_MONTHS: 72
    command: 'run start-dev'

  tr-react:
    image: teemaderegister-react
    container_name: "tr-react"
    depends_on:
      - tr-node
    build:
      context: '../teemaderegister-react'
    ports:
      - "3446:3446"
    volumes:
      - '../teemaderegister-react:/home/node/app:delegated'
    environment:
        GA_CODE: 'UA-000000000-0'
        GA_ENABLED: 'false'
        FACULTY: 'DTI'
        UPLOAD_PATH: '/uploads/'
        PROFILE_PIC_MAX_SIZE_IN_MB: 10
    command: run dev
  
  tr-nginx:
    image: nginx
    container_name: "tr-nginx"
    depends_on:
      - tr-react
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/uploads:/var/www/data/uploads
