// auth
export const AUTH_START = 'AUTH_START'
export const AUTH_LOADED = 'AUTH_LOADED'
export const AUTH_INIT = 'AUTH_INIT'

// curriculum
export const CURRICULUM_LOADED = 'CURRICULUM_LOADED'
export const CURRICULUM_INIT = 'CURRICULUM_INIT'
export const CURRICULUM_ADD_START = 'CURRICULUM_ADD_START'
export const CURRICULUM_ADD_END = 'CURRICULUM_ADD_END'


//topcis
export const TOPIC_ADD_START = 'TOPIC_ADD_START'
export const TOPIC_ADD_END = 'TOPIC_ADD_END'

// home
export const CURRICULUMS_LOADED = 'CURRICULUMS_LOADED'

// login
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_LOADED = 'LOGIN_LOADED'
export const LOGIN_INIT = 'LOGIN_INIT'

// password
export const PASSWORD_RESET_LINK_SENDING = 'PASSWORD_RESET_LINK_SENDING'
export const PASSWORD_RESET_LINK_SENT = 'PASSWORD_RESET_LINK_SENT'
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR'
export const PASSWORD_RESET_START = 'PASSWORD_RESET_START'
export const PASSWORD_RESET_FORM = 'PASSWORD_RESET_FORM'
export const PASSWORD_RESET_END = 'PASSWORD_RESET_END'
export const PASSWORD_RESET_INIT = 'PASSWORD_RESET_INIT'

// search
export const SEARCH_SET = 'SEARCH_SET'
export const SEARCH_START = 'SEARCH_START'
export const SEARCH_LOADED = 'SEARCH_LOADED'
export const SEARCH_INIT = 'SEARCH_INIT'

// supervisor
export const SUPERVISOR_LOADED = 'SUPERVISOR_LOADED'
export const SUPERVISOR_INIT = 'SUPERVISOR_INIT'

// tableContent
export const TABLE_COUNT_LOADED = 'TABLE_COUNT_LOADED'
export const TABLE_START = 'TABLE_START'
export const TABLE_CLEAR = 'TABLE_CLEAR'
export const TABLE_LOADED = 'TABLE_LOADED'
export const TABLE_INIT = 'TABLE_INIT'

// terms of service
export const TOS_LOADED = 'TOS_LOADED'
export const TOS_SAVED = 'TOS_SAVED'

// settings
export const USER_SETTINGS_LOADED = 'USER_SETTINGS_LOADED'
export const USER_SETTINGS_INIT = 'USER_SETTINGS_INIT'

export const USER_SETTINGS_SAVE_START = 'USER_SETTINGS_SAVE_START'
export const USER_SETTINGS_SAVE_END = 'USER_SETTINGS_SAVE_END'

export const USER_PICTURE_SET_START = 'USER_PICTURE_SET_START'
export const USER_PICTURE_SET_END = 'USER_PICTURE_SET_END'

export const PASSWORD_CHANGE_START = 'PASSWORD_CHANGE START'
export const PASSWORD_CHANGE_END = 'PASSWORD_CHANGE_END'